# Generated by Django 3.2 on 2022-03-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userdata_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='is_active',
        ),
    ]
