# Generated by Django 3.2 on 2022-03-30 19:53

import api.utilites
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_userdata_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=api.utilites.timestapppp, verbose_name='Аватар'),
        ),
    ]
